-- insert into annonce
-- values ('id1', 'Annonce 1', 105, 'description 1', 'VEHICULE');
--
-- insert into annonce
-- values ('id2', 'Annonce 2', 2000, 'description 2', 'IMMOBILIER');
--
-- insert into annonce
-- values ('id3', 'Annonce 3', 25, 'description 3', 'IMMOBILIER');
